terraform_outputs: "{{ lookup('file', 'group_vars/web.json') | from_json }}"

db_host: "{{ terraform_outputs.dbhost.value }}"
db_username: "{{ terraform_outputs.dbuser.value }}"
db_password: "{{ terraform_outputs.dbpass.value }}"
db_name: "{{ terraform_outputs.dbname.value }}"
web_public_ip: "{{ terraform_outputs.public_ip.value }}"

app_dir: /opt/epicbook
web_root: /var/www/html
